# Generated by Django 4.0.6 on 2022-09-11 22:56

from django.db import migrations, models

import apps.humans.models


class Migration(migrations.Migration):

    dependencies = [
        ("humans", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="human",
            name="avatar",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to=apps.humans.models.get_icon_path, verbose_name="Avatar"
            ),
        ),
    ]
