# Generated by Django 4.0.6 on 2022-09-15 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user", models.CharField(max_length=200, verbose_name="User")),
                ("request_path", models.CharField(max_length=200, verbose_name="Request Path")),
                ("request_count", models.PositiveIntegerField(default=1, verbose_name="Number of requests")),
                (
                    "last_visit",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2022, 9, 15, 0, 13, 19, 179705),
                        null=True,
                        verbose_name="Last Visit",
                    ),
                ),
            ],
        ),
    ]
