# Generated by Django 4.0.6 on 2022-09-15 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("middleware_logger", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestlog",
            name="last_visit",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 9, 15, 0, 13, 22, 167692),
                null=True,
                verbose_name="Last Visit",
            ),
        ),
    ]
